version: '3.5'
services:
  web:
    build:
      context: ./
      dockerfile: .docker/web.docker
    volumes:
      - ./:/var/www:cached
    ports:
      - '9080:80'
    links:
      - app
  app:
    build:
      context: ./
      dockerfile: .docker/app.docker
    extra_hosts:
      - "payment.test:host-gateway"
    volumes:
      - ./:/var/www:cached
    links:
      - database
      - cache
    platform: linux/x86_64
  database:
    image: mysql:latest
    platform: linux/x86_64
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql_mode=""
    environment:
      - 'MYSQL_ROOT_PASSWORD=V3pdNJauyMeDlAb9uMUjxw1L4raCA5UE'
      - 'MYSQL_DATABASE=shorten'
    ports:
      - '45000:3306'
    volumes:
      - './.docker/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
  cache:
    image: redis:latest
    ports:
      - '64000:6379'
